server:
  port: 8085
  servlet:
    context-path: /SpringBootCRUDApp
---
spring:
  profiles: local,default
  datasource:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
      hibernate.default_schema:
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/websystique
    username: root
    password: root1234
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.defaultSchema: true
    database-platform: org.hibernate.dialect.MySQLDialect
