spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/websystique
    username: root
    password: root1234
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.defaultSchema:
    database-platform: org.hibernate.dialect.MySQLDialect
